// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Device       pgtype.Text        `json:"device"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	RefreshToken string             `json:"refresh_token"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	FullName    pgtype.Text        `json:"full_name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Role        string             `json:"role"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type UserMetadatum struct {
	UserID    uuid.UUID          `json:"user_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
